spring:
  profiles:
    active: prod

  datasource:
    username: fields_code
    password: Fields+123
    url: jdbc:mysql://rm-uf68frea8d8ny3sn8ao.mysql.rds.aliyuncs.com:3306/wind?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
#    default-property-inclusion: non_null

server:
  port: 8080

python:
  script: D:/REINS/MinHuan/ai-platform-metadata/src/main/resources/scripts/
